<?php
/**
 * BudgetsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BudgetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BudgetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for usersUserGuidBudgetsBudgetGuidDelete
     *
     * Delete a budget.
     *
     */
    public function testUsersUserGuidBudgetsBudgetGuidDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserGuidBudgetsBudgetGuidGet
     *
     * Read a specific budget.
     *
     */
    public function testUsersUserGuidBudgetsBudgetGuidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserGuidBudgetsBudgetGuidPut
     *
     * Update a specific budget.
     *
     */
    public function testUsersUserGuidBudgetsBudgetGuidPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserGuidBudgetsGeneratePost
     *
     * Auto-generate budgets.
     *
     */
    public function testUsersUserGuidBudgetsGeneratePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserGuidBudgetsGet
     *
     * List all budgets.
     *
     */
    public function testUsersUserGuidBudgetsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for usersUserGuidBudgetsPost
     *
     * Create a budget.
     *
     */
    public function testUsersUserGuidBudgetsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
